In [25]:
import os
import json
import pandas as pd
import re
import numpy as np


# Connect to Google Drive
import gspread
import gspread_dataframe
from google.oauth2.service_account import Credentials
from google.oauth2 import service_account
from googleapiclient.discovery import build
from gspread_dataframe import set_with_dataframe
from gspread_dataframe import get_as_dataframe

In [ ]:
# 1. Fetch credentials from environment variable
creds_env = os.environ.get("GDRIVE_CREDENTIALS_KC")

if not creds_env:
    raise ValueError("Environment variable 'GDRIVE_CREDENTIALS' was not found.")

creds_json = json.loads(creds_env)

# 2. Define required scopes
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

# 3. Authenticate service account
creds = service_account.Credentials.from_service_account_info(
    creds_json, scopes=scopes
)

# 4. Initialize Google API clients
drive_service = build("drive", "v3", credentials=creds)
sheets_service = build("sheets", "v4", credentials=creds)

gc = gspread.authorize(creds)

print("Google Drive and Sheets services successfully initialized.")

Mounted at /content/drive

In [28]:
# Open files

forms_data = gc.open_by_key('1xmm88zF84MEk-7ZwARh6ZCFcaI2SmW8c7Dnlwe4zGr4')
forms_data = forms_data.get_worksheet(0)
forms_data = get_as_dataframe(forms_data)

influencers_posts = gc.open_by_key('1ckdCSF1JD_SMkBNPuLfb0FdsuHQ9wXkL4u2NoLWe8aQ')
influencers_posts = influencers_posts.get_worksheet(0)
influencers_posts = get_as_dataframe(influencers_posts)

influencers_comments = gc.open_by_key('1a592d89m2sCmcxuKqF2SeJRGFUYanZIXo0RKOxmVVpU')
influencers_comments = influencers_comments.get_worksheet(0)
influencers_comments = get_as_dataframe(influencers_comments)

posts_data = gc.open_by_key('1GWe4XOZatmvNknH6GmvrEKnDjNSTUK4OOQoqV4So0zQ')
posts_data = posts_data.worksheet('tt_data_post_post_max')
posts_data = get_as_dataframe(posts_data)

posts_comments = gc.open_by_key('1nHmuARdf6vLGGZw2ykXlL5zJ_KOa15-7BARxGHaGP2U')
posts_comments = posts_comments.get_worksheet(0)
posts_comments = get_as_dataframe(posts_comments)

In [29]:
# Clean databases
forms_data = forms_data.fillna(0)
influencers_posts = influencers_posts.fillna(0)
influencers_comments = influencers_comments.fillna(0)
posts_data = posts_data.fillna(0)
posts_comments = posts_comments.fillna(0)

/tmp/ipykernel_2580/135062332.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  posts_comments = posts_comments.fillna(0)

In [30]:
# Consolidate sentiment for each published post
posts_comments = posts_comments.rename(columns={'username': 'commenter'})
posts_comments = posts_comments.merge(posts_data[["video_url", "username"]], on='video_url', how='left')
sentiment_posts = posts_comments.groupby(['video_url', 'username']).agg(
    positive_count=('classification', lambda x: x.isin(['promotor', 'Promoter', 'promoter', 'Promotor']).sum()),
    negative_count=('classification', lambda x: x.isin(['detrator', 'Detractor', 'detractor', 'Detractor']).sum()),
    neutral_count=('classification', lambda x: x.isin(['neutro', 'neutral', 'Neutro', 'Neutral']).sum()),
).reset_index()
# 2. Sum the three sentiment columns to get the total
sentiment_posts['total_sentiments'] = (
    sentiment_posts['positive_count'] +
    sentiment_posts['negative_count'] +
    sentiment_posts['neutral_count']
)

# 3. Calculate the percentage of each sentiment over the total
sentiment_posts['positive_percentage'] = sentiment_posts['positive_count'] / sentiment_posts['total_sentiments']
sentiment_posts['negative_percentage'] = sentiment_posts['negative_count'] / sentiment_posts['total_sentiments']
sentiment_posts['neutral_percentage'] = sentiment_posts['neutral_count'] / sentiment_posts['total_sentiments']

In [31]:
sentiment_posts

,video_url,username,positive_count,negative_count,neutral_count,total_sentiments,positive_percentage,negative_percentage,neutral_percentage
0,https://www.tiktok.com/@_dulcepink_/video/7608...,_dulcepink_,24,15,12,51,0.470588,0.294118,0.235294
1,https://www.tiktok.com/@_dulcepink_/video/7612...,_dulcepink_,35,50,15,100,0.350000,0.500000,0.150000
2,https://www.tiktok.com/@benjacaldero/video/760...,benjacaldero,36,16,48,100,0.360000,0.160000,0.480000
3,https://www.tiktok.com/@benjacaldero/video/761...,benjacaldero,32,36,32,100,0.320000,0.360000,0.320000
4,https://www.tiktok.com/@caam.prz/video/7608226...,caam.prz,2,3,2,7,0.285714,0.428571,0.285714
5,https://www.tiktok.com/@caam.prz/video/7609874...,caam.prz,32,43,25,100,0.320000,0.430000,0.250000
6,https://www.tiktok.com/@crispierri/video/76083...,crispierri,3,4,13,20,0.150000,0.200000,0.650000
7,https://www.tiktok.com/@davooxeneize/video/765...,davooxeneize,27,58,15,100,0.270000,0.580000,0.150000
8,https://www.tiktok.com/@davooxeneize/video/765...,davooxeneize,35,48,17,100,0.350000,0.480000,0.170000
9,https://www.tiktok.com/@florjazminp/video/7642...,florjazminp,47,43,10,100,0.470000,0.430000,0.100000
10,https://www.tiktok.com/@gastiobeide/video/7608...,gastiobeide,6,2,10,18,0.333333,0.111111,0.555556
11,https://www.tiktok.com/@gastiobeide/video/7610...,gastiobeide,22,55,23,100,0.220000,0.550000,0.230000
12,https://www.tiktok.com/@gastonedul/video/76425...,gastonedul,27,49,24,100,0.270000,0.490000,0.240000
13,https://www.tiktok.com/@gastonedul/video/76524...,gastonedul,24,15,20,59,0.406780,0.254237,0.338983
14,https://www.tiktok.com/@holaestapablo_ok/video...,holaestapablo_ok,2,0,1,3,0.666667,0.000000,0.333333
15,https://www.tiktok.com/@laagusneta/video/76428...,laagusneta,22,32,26,80,0.275000,0.400000,0.325000
16,https://www.tiktok.com/@lacobraaa.9/video/7650...,lacobraaa.9,13,64,23,100,0.130000,0.640000,0.230000
17,https://www.tiktok.com/@lacobraaa.9/video/7660...,lacobraaa.9,18,58,24,100,0.180000,0.580000,0.240000
18,https://www.tiktok.com/@losariasbrothers/video...,losariasbrothers,43,7,21,71,0.605634,0.098592,0.295775
19,https://www.tiktok.com/@lucaslezin/video/76101...,lucaslezin,11,42,13,66,0.166667,0.636364,0.196970
20,https://www.tiktok.com/@lulignzalez/video/7644...,lulignzalez,29,9,7,45,0.644444,0.200000,0.155556
21,https://www.tiktok.com/@lulignzalez/video/7656...,lulignzalez,24,6,6,36,0.666667,0.166667,0.166667
22,https://www.tiktok.com/@owenn_27/video/7645441...,owenn_27,12,5,9,26,0.461538,0.192308,0.346154
23,https://www.tiktok.com/@owenn_27/video/7653281...,owenn_27,16,7,7,30,0.533333,0.233333,0.233333
24,https://www.tiktok.com/@pablobruschiok/video/7...,pablobruschiok,21,15,13,49,0.428571,0.306122,0.265306
25,https://www.tiktok.com/@pablobruschiok/video/7...,pablobruschiok,44,32,24,100,0.440000,0.320000,0.240000
26,https://www.tiktok.com/@robergalati/video/7641...,robergalati,29,42,20,91,0.318681,0.461538,0.219780

In [32]:
# Prepare datasets for join

posts_data = posts_data.rename(columns={'username': 'influencer'})
posts_data = posts_data.rename(columns={'video_url': 'url'})
forms_data = forms_data.rename(columns={'Link of Post': 'url'})
sentiment_posts = sentiment_posts.rename(columns={'video_url': 'url'})
influencers_posts_join = (
    influencers_posts[["username", "followers"]]
    .drop_duplicates(subset="username")
    .rename(columns={"username": "influencer"})
)

In [33]:
# Join datasets
tiktok_influencers_final = posts_data
tiktok_influencers_final = tiktok_influencers_final.merge(forms_data, on='url', how='left')
tiktok_influencers_final = tiktok_influencers_final.merge(sentiment_posts, on='url', how='left')
tiktok_influencers_final = tiktok_influencers_final.merge(influencers_posts_join, on='influencer', how='left')

tiktok_influencers_final

,url,influencer,run_datetime,aweme_id,likes,comment_count,share_count,views,saves,download_count,...,Budget: AON / campaña,username,positive_count,negative_count,neutral_count,total_sentiments,positive_percentage,negative_percentage,neutral_percentage,followers
0,https://www.tiktok.com/@robergalati/video/7641...,robergalati,2026-08-26 12:49:11,7.641638e+18,32936.0,113.0,1791.0,24243357.0,3018.0,51.0,...,0.0,robergalati,29.0,42.0,20.0,91.0,0.318681,0.461538,0.219780,37265.0
1,https://www.tiktok.com/@florjazminp/video/7642...,florjazminp,2026-08-26 12:50:12,7.642103e+18,49120.0,456.0,531.0,5456485.0,1564.0,9.0,...,0.0,florjazminp,47.0,43.0,10.0,100.0,0.470000,0.430000,0.100000,1814675.0
2,https://www.tiktok.com/@gastonedul/video/76425...,gastonedul,2026-08-26 12:51:07,7.642503e+18,25920.0,251.0,503.0,6164281.0,1144.0,6.0,...,0.0,gastonedul,27.0,49.0,24.0,100.0,0.270000,0.490000,0.240000,2111301.0
3,https://www.tiktok.com/@gastonedul/video/76524...,gastonedul,2026-08-26 12:52:01,7.652461e+18,8390.0,94.0,22.0,80064.0,225.0,5.0,...,0.0,gastonedul,24.0,15.0,20.0,59.0,0.406780,0.254237,0.338983,2111301.0
4,https://www.tiktok.com/@laagusneta/video/76428...,laagusneta,2026-08-26 12:52:41,7.642804e+18,25873.0,137.0,1126.0,9196369.0,1382.0,8.0,...,0.0,laagusneta,22.0,32.0,26.0,80.0,0.275000,0.400000,0.325000,551389.0
5,https://www.tiktok.com/@owenn_27/video/7645441...,owenn_27,2026-08-26 12:53:30,7.645441e+18,5747.0,40.0,24.0,113871.0,187.0,6.0,...,0.0,owenn_27,12.0,5.0,9.0,26.0,0.461538,0.192308,0.346154,5826203.0
6,https://www.tiktok.com/@owenn_27/video/7653281...,owenn_27,2026-08-26 12:53:55,7.653281e+18,2902.0,34.0,36.0,51360.0,129.0,3.0,...,0.0,owenn_27,16.0,7.0,7.0,30.0,0.533333,0.233333,0.233333,5826203.0
7,https://www.tiktok.com/@lulignzalez/video/7644...,lulignzalez,2026-08-26 12:54:15,7.644266e+18,12983.0,53.0,62.0,115636.0,194.0,12.0,...,0.0,lulignzalez,29.0,9.0,7.0,45.0,0.644444,0.200000,0.155556,1569717.0
8,https://www.tiktok.com/@lulignzalez/video/7656...,lulignzalez,2026-08-26 12:54:50,7.656832e+18,7585.0,46.0,48.0,77667.0,121.0,3.0,...,0.0,lulignzalez,24.0,6.0,6.0,36.0,0.666667,0.166667,0.166667,1569717.0
9,https://www.tiktok.com/@lacobraaa.9/video/7650...,lacobraaa.9,2026-08-26 12:55:20,7.650666e+18,60006.0,795.0,1407.0,8142117.0,2115.0,13.0,...,0.0,lacobraaa.9,13.0,64.0,23.0,100.0,0.130000,0.640000,0.230000,4382721.0
10,https://www.tiktok.com/@lacobraaa.9/video/7660...,lacobraaa.9,2026-08-26 12:56:10,7.660926e+18,88991.0,764.0,1254.0,511763.0,3820.0,56.0,...,0.0,lacobraaa.9,18.0,58.0,24.0,100.0,0.180000,0.580000,0.240000,4382721.0
11,https://www.tiktok.com/@davooxeneize/video/765...,davooxeneize,2026-08-26 12:57:09,7.652157e+18,9767.0,290.0,144.0,117970.0,280.0,3.0,...,0.0,davooxeneize,27.0,58.0,15.0,100.0,0.270000,0.580000,0.150000,3941224.0
12,https://www.tiktok.com/@davooxeneize/video/765...,davooxeneize,2026-08-26 12:58:13,7.659478e+18,11214.0,218.0,55.0,154603.0,223.0,4.0,...,0.0,davooxeneize,35.0,48.0,17.0,100.0,0.350000,0.480000,0.170000,3941224.0
13,https://www.tiktok.com/@_dulcepink_/video/7608...,_dulcepink_,2026-08-26 12:59:10,7.608292e+18,109462.0,209.0,501.0,1195000.0,1787.0,29.0,...,0.0,_dulcepink_,24.0,15.0,12.0,51.0,0.470588,0.294118,0.235294,2534839.0
14,https://www.tiktok.com/@crispierri/video/76083...,crispierri,2026-08-26 12:59:51,7.608334e+18,7450.0,110.0,144.0,698846.0,310.0,2.0,...,0.0,crispierri,3.0,4.0,13.0,20.0,0.150000,0.200000,0.650000,3298963.0
15,https://www.tiktok.com/@pablobruschiok/video/7...,pablobruschiok,2026-08-26 13:00:20,7.608329e+18,62622.0,163.0,1954.0,1005826.0,3153.0,34.0,...,0.0,pablobruschiok,21.0,15.0,13.0,49.0,0.428571,0.306122,0.265306,15252077.0
16,https://www.tiktok.com/@benjacaldero/video/760...,benjacaldero,2026-08-26 13:00:49,7.608322e+18,23311.0,316.0,190.0,665633.0,1830.0,12.0,...,0.0,benjacaldero,36.0,16.0,48.0,100.0,0.360000,0.160000,0.480000,6200892.0
17,https://www.tiktok.com/@losariasbrothers/video...,losariasbrothers,2026-08-26 13:01:51,7.608321e+18,9746.0,83.0,392.0,279737.0,709.0,36.0,...,0.0,losariasbrothers,43.0,7.0,21.0,71.0,0.605634,0.098592,0.295775,5418179.0
18,https://www.tiktok.com/@caam.prz/video/7608226...,caam.prz,2026-08-26 13:02:54,7.608226e+18,3739.0,32.0,61.0,288684.0,106.0,0.0,...,0.0,caam.prz,2.0,3.0,2.0,7.0,0.285714,0.428571,0.285714,834788.0
19,https://www.tiktok.com/@gastiobeide/video/7608...,gastiobeide,2026-08-26 13:03:08,7.608299e+18,6122.0,119.0,168.0,511435.0,406.0,6.0,...,0.0,gastiobeide,6.0,2.0,10.0,18.0,0.333333,0.111111,0.555556,1976676.0
20,https://www.tiktok.com/@_dulcepink_/video/7612...,_dulcepink_,2026-08-26 13:03:33,7.612302e+18,102590.0,272.0,1425.0,7283968.0,2627.0,11.0,...,0.0,_dulcepink_,35.0,50.0,15.0,100.0,0.350000,0.500000,0.150000,2534839.0
21,https://www.tiktok.com/@crispierri/video/76124...,crispierri,2026-08-26 13:05:02,7.612412e+18,8268.0,85.0,280.0,5094100.0,519.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298963.0
22,https://www.tiktok.com/@benjacaldero/video/761...,benjacaldero,2026-08-26 13:05:40,7.612445e+18,45420.0,283.0,1063.0,5956783.0,3054.0,25.0,...,0.0,benjacaldero,32.0,36.0,32.0,100.0,0.320000,0.360000,0.320000,6200892.0
23,https://www.tiktok.com/@pablobruschiok/video/7...,pablobruschiok,2026-08-26 13:06:33,7.612410e+18,34357.0,238.0,737.0,5796019.0,2302.0,45.0,...,0.0,pablobruschiok,44.0,32.0,24.0,100.0,0.440000,0.320000,0.240000,15252077.0
24,https://www.tiktok.com/@holaestapablo_ok/video...,holaestapablo_ok,2026-08-26 13:07:27,7.612314e+18,3851.0,3.0,11.0,105465.0,119.0,7.0,...,0.0,holaestapablo_ok,2.0,0.0,1.0,3.0,0.666667,0.000000,0.333333,460468.0
25,https://www.tiktok.com/@lucaslezin/video/76101...,lucaslezin,2026-08-26 13:07:38,7.610109e+18,13863.0,113.0,2067.0,9290459.0,956.0,29.0,...,0.0,lucaslezin,11.0,42.0,13.0,66.0,0.166667,0.636364,0.196970,970292.0
26,https://www.tiktok.com/@caam.prz/video/7609874...,caam.prz,2026-08-26 13:08:36,7.609874e+18,45638.0,156.0,1152.0,9639537.0,1834.0,8.0,...,0.0,caam.prz,32.0,43.0,25.0,100.0,0.320000,0.430000,0.250000,834788.0
27,https://www.tiktok.com/@gastiobeide/video/7610...,gastiobeide,2026-08-26 13:09:31,7.610083e+18,29574.0,239.0,2391.0,15588917.0,2707.0,14.0,...,0.0,gastiobeide,22.0,55.0,23.0,100.0,0.220000,0.550000,0.230000,1976676.0

In [34]:
# Create Organic_id
tiktok_influencers_final["Organic_ID"] = tiktok_influencers_final["aweme_id"]
tiktok_influencers_final['Organic_ID'] = tiktok_influencers_final['Organic_ID'].astype('string')

In [35]:
# Rename columns
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'desc': 'copy'})
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'Published date': 'date_published'})
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'Plataform': 'platform'})
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'comment_count': 'comments'})
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'share_count': 'shares'})
tiktok_influencers_final = tiktok_influencers_final.rename(columns={'Marca': 'brand'})

In [36]:
# Crear columnas

tiktok_influencers_final["content_type"] = "Influencers"
tiktok_influencers_final["format"] = "Video"
tiktok_influencers_final["total_interactions"] = tiktok_influencers_final["likes"] + tiktok_influencers_final["comments"] + tiktok_influencers_final["shares"] + tiktok_influencers_final["saves"]
tiktok_influencers_final["engagement_rate"] = (
    tiktok_influencers_final["total_interactions"]
    .div(tiktok_influencers_final["views"])
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)
tiktok_influencers_final["positive_comments"] = tiktok_influencers_final["positive_percentage"] * tiktok_influencers_final["comments"]
tiktok_influencers_final["negative_comments"] = tiktok_influencers_final["negative_percentage"] * tiktok_influencers_final["comments"]
tiktok_influencers_final["neutral_comments"] = tiktok_influencers_final["neutral_percentage"] * tiktok_influencers_final["comments"]

In [37]:
# Seleccionar y ordenar columnas

cols = [
    "url",
    "copy",
    "date_published",
    "platform",
    "format",
    "influencer",
    "Country",
    "Organic_ID",
    "brand",
    "content_type",
    "views",
    "likes",
    "comments",
    "shares",
    "saves",
    "total_interactions",
    "engagement_rate",
    "positive_percentage",
    "negative_percentage",
    "neutral_percentage",
    "positive_comments",
    "negative_comments",
    "neutral_comments",
    "run_datetime",
    "followers"
]

tiktok_influencers_final = tiktok_influencers_final[cols]
tiktok_influencers_final = tiktok_influencers_final.reindex(columns=cols)

In [38]:
# Adjust date
tiktok_influencers_final["date_published"] = pd.to_datetime(
    tiktok_influencers_final["date_published"],
    format="mixed",
    errors="coerce",
).dt.date

In [40]:
# Save final table
# Open the destination sheets file
sh = gc.open_by_key('1FAVS_dtKl5WPoXeqpa5JGPbSe7tVv7GhumQvkUOSxiw')
worksheet = sh.get_worksheet(0)

# Replace old data with new data
set_with_dataframe(worksheet, tiktok_influencers_final)
print("DataFrame saved successfully!")

DataFrame saved successfully!